Layout
jcromerohdz/design_teardown pull request #1
Opened 2019-09-03 21:52 UTC by jcromerohdz

2019-09-03 23:52 UTC, uche-inyama reviewed
## Pull request under review by: Inyama, Uchechukwu Henry

2019-09-04 00:48 UTC, uche-inyama requested changes
## Nice work team :+1: 
### But there are changes to implement
- [x] Validate your html file. [Html Validator](https://validator.w3.org) Ensure there are no errors.
- [x] Usage of semantic html, you forgot to add ```<main>``` *tag* to specify the main content of your html document.
- [x] In your navigation section, the ```<nav>``` *tag* should use a ```<div>``` *tag* to position elements.  Inspect the source page and use it a reference.
 - [x] Add more contents to your README
     * Add the link to Odin project for vistors to your github account to get more information
     * You can write a terse of what Tear-down is, because it is not your usual website :smiley: 
     * [**optional**] Add any detail you think would inform those that are going through your project.
### Implement these changes and submit another form for code review :muscle: :fire: 

#### Cheers Henry :smiley:

2019-09-04 20:41 UTC, samgaco approved these changes
#### Hi @jcromerohdz and @lhscar56 :high_brightness: 

#### All the requested changes have been implemented therefore you are approved :100: Congratulations :1st_place_medal: 

**[OPTIONAL]** As a suggestion I would tell you to improve the readme file, you still can add your contact details, more information, what have you used to achieve it, what is the project about, etc. You can find inspiration in readme templates like [this one](https://github.com/othneildrew/Best-README-Template) or free courses like [this one.](https://www.udacity.com/course/writing-readmes--ud777)


--------------

* **[For your next code review requests]**  Use meaningful names for your Pull Requests
* **[For your next code review requests]**  Add a short summary of changes in Pull Request description
* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-09-04 20:41 UTC, samgaco commented on README.md
> +[To more info ](https://www.theodinproject.com/courses/html5-and-css3/lessons/design-teardown
You haven't closed the last parenthesis

2019-09-04 20:49 UTC, merged